### ISSUE TITLE
Memory access out of bounds

### ISSUE THREAD

**Issue by CrossStyle** [tomvandig/web-ifc#55] opened 2021-06-24 09:02 UTC
Hello,

I had a problem when I tried to open an [IFC](https://github.com/CrossStyle/BIM-Viewer/blob/8eb69a0f2c928b251404ffa1d502942214c8e2db/local_app/9-6TH%20FLOOR.ifc) file that was part of a model.

```
web-ifc.wasm:0x8533 Uncaught RuntimeError: memory access out of bounds
    at web-ifc.wasm:0x8533
    at web-ifc.wasm:0x3dc7b
    at web-ifc.wasm:0x26629
    at Object.LoadAllGeometry (eval at new_ (web-ifc-viewer.js:3754), <anonymous>:8:10)
    at IfcAPI.LoadAllGeometry (web-ifc-viewer.js:74215)
    at IfcThree.getFlatMeshes (web-ifc-viewer.js:74243)
    at IfcThree.LoadAllGeometry (web-ifc-viewer.js:74232)
    at LoadModel (web-ifc-viewer.js:98567)
    at FileReader.reader.onload (web-ifc-viewer.js:98550)
```

**Comment by tomvandig** [comment] 2021-06-24 16:23
Your model has a line like this:
#50107=IFCRELVOIDSELEMENT('0MlN48Dwn3nfScny$3iZ$u',#6,$,$,#4126,$);
The last element is empty, but this is not allowed by the spec: https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/schema/ifcproductextension/lexical/ifcrelvoidselement.htm

I suggest that you fix the file to be compliant.

However, I would still like to parse this file normally even though references are missing/wrong, so I will keep this issue open until I solve it.

**Comment by ABaaS-dev** [comment] 2021-07-21 16:50
Hello,
I am facing a similar issue but I checked in my file, the last element of all the IFCRELVOIDSELEMENT tags is filled.
Moreover, I'm only facing the issue with the 21 version (not with the 20).

Did you already identified some king of regression with the new version ?

Thanks

**Comment by tomvandig** [comment] 2021-07-21 19:22
Hi, please attach your model so I can take a look. Thx!

**Comment by ABaaS-dev** [comment] 2021-07-22 08:33
Hi Tom,
I cannot share my file publicly, is there a way I can send it to you directly ?
Thanks

**Comment by tomvandig** [comment] 2021-07-22 19:05
Easiest thing would be to join the discord channel, and find me:
https://discord.com/invite/g7Uzn2KSwB

Thanks!

**Comment by RedTurkey** [comment] 2022-04-28 07:47
Just commenting to tell that I also encountered this problem, but it seems that it was because I was using an previous version of Node.js (10....), and when switching to a more recent version (16.15.0), it worked perfectly.

**Comment by agviegas** [comment] 2022-05-15 20:22
Hi,  this should be solved now, so I'm closing this issue. 

![image](https://user-images.githubusercontent.com/56475338/168492369-c38c19e6-6be5-4fdc-9c28-3ef1aca09e8f.png)

**Closed by agviegas** 2022-05-15 20:22 UTC
