### ISSUE TITLE
Critical dependency: the request of a dependency is an expression in web-ifc-api.js

### ISSUE THREAD

**Issue by camnewnham** [tomvandig/web-ifc#82] opened 2021-09-12 04:47 UTC
Since updating to `threejs 0.132.2` in a `create-react-app` / `webpack` project receiving the warning:

```
./node_modules/three/examples/jsm/loaders/ifc/web-ifc-api.js     
Critical dependency: the request of a dependency is an expression
```

Builds still succeed, but by default most CI servers will `set CI=true`, resulting in warnings treated as errors (as I experienced with GitHub Actions).

This can be avoided in the short term by setting `CI=false` on the build server, but of course, this is not an ideal configuration for CI!

It seems to have been introduced with this update to threejs: https://github.com/mrdoob/three.js/pull/22352

**Comment by favreau84** [comment] 2021-09-20 07:22
As @camnewnham mentioned, I had to set `CI=false` so that builds succeed...Not ideal ! Any idea on how this warning could be removed ?

**Comment by pablo-mayrgundter** [comment] 2021-09-23 14:01
Still seeing this too with web-ifc-viewer@1.0.64

**Comment by pablo-mayrgundter** [comment] 2021-09-23 14:24
Ah, isn't this a dupe of https://github.com/IFCjs/web-ifc-viewer/issues/88?  It was a won't fix.

**Comment by agviegas** [comment] 2021-09-23 17:12
Yeap, indeed. This code is autogenerated by emscripteen and we don't have control over it. Anyway, it's a false positive, as that code will only execute in node apps.

**Closed by agviegas** 2021-09-23 17:12 UTC

**Comment by suryakumara** [comment] 2022-07-14 04:32
Facing this warning too in Create React App.

**Comment by agviegas** [comment] 2022-07-28 08:13
Yep, nothing we can do about this warning, as this code is autogenerated by Emscripten. Nevertheless, it should work fine.

**Comment by wojciechteclaw** [comment] 2023-01-23 22:28
Could you let me know if you solved this issue while working with webpack?

After installing `web-ifc@0.0.36`  and importing it to a project instantly I'm getting an error:

```
WARNING in ./node_modules/web-ifc/web-ifc-api.js 19:11-21

Critical dependency: the request of a dependency is an expression
```

This is my webpack.config.js:

```
const HTMLWebpackPlugin = require("html-webpack-plugin");
const path = require("path");

module.exports = {
    plugins: [
        new HTMLWebpackPlugin({
            template: "./src/index.html",
        }),
    ],
    mode: 'development',
    entry: './src/index.tsx',
    devServer:{
      port: 3001,
      open: true,
      hot: true,
    },
    module: {
        rules: [
            {
                test: /.(js|jsx)$/,
                exclude: /node_modules/,
                use: {
                    loader: "babel-loader",
                },
            },
            {
                test: /.(ts|tsx)$/,
                exclude: /node_modules/,
                use: {
                    loader: "ts-loader",
                },
            },
            {
                test: /\.css$/i,
                use: ["style-loader", "css-loader"],
            },
        ],
    },
    resolve: {
        alias: {
            "@components": path.resolve(process.cwd(), "./src/components/"),
            "@services": path.resolve(process.cwd(), "./src/services/"),
        },
        extensions: [".tsx", ".ts", ".jsx", ".js"],
    },
};



```

Do you have any suggestions which can help me to solve the issue? 
Is any method available allowing me to work with the library + TS + webpack?

**Comment by Tamu** [comment] 2023-03-20 14:30
@wojciechteclaw have you found any solution !? I have the same question !

**Comment by wojciechteclaw** [comment] 2023-03-20 18:22
@Tamu, I cannot fix the problem except the rebuilding the library by myself.
However, one solution is to hide the error message by adding to your webpack.dev.js the following line:
`
client: {
    overlay: false,
},
`

**Comment by Tamu** [comment] 2023-03-20 19:02
Thanks @wojciechteclaw for your experience and the good idea !
